export const services = [
    'PEST_CONTROL', 'PRESSURE_WASHING', 'HANDYMAN', 'INTERIOR_CLEANING', 'CARPET_CLEANING',
    'LAWN_MAINTENANCE', 'HVAC', 'ELECTRICAL', 'PLUMBING', 'WINDOW_CLEANING', 'GUTTER_CLEANING',
    'POOL_MAINTENANCE', 'GARAGE_DOORS', 'FLOORING', 'PAINTING_INTERIOR', 'PAINTING_EXTERIOR', 'ENVIRONMENTAL',
  ];

  export const servicesMyQuotes = [
    'All', 'PEST_CONTROL', 'PRESSURE_WASHING', 'HANDYMAN', 'INTERIOR_CLEANING', 'CARPET_CLEANING',
    'LAWN_MAINTENANCE', 'HVAC', 'ELECTRICAL', 'PLUMBING', 'WINDOW_CLEANING', 'GUTTER_CLEANING',
    'POOL_MAINTENANCE', 'GARAGE_DOORS', 'FLOORING', 'PAINTING_INTERIOR', 'PAINTING_EXTERIOR', 'ENVIRONMENTAL',
  ];